# Generated by Django 4.0.4 on 2022-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('msg', models.TextField(max_length=500)),
            ],
        ),
    ]
